### ISSUE TITLE
Thanks for setting this up. 

### ISSUE THREAD

**Issue by andrewabogado** [pgdureza/gulp-local-hubl#1]
Thanks for setting this up. Do you mind sharing some tips on how to add images to gulp with compression and all? I'm curious if this is necessary or does Hubspot does the compression?

**Comment by pgdureza** [comment]
Hey Andrew. Hubspot already does all that for you. You can simply indicate the wanted width and height on the url when requesting image assets and it should dynamically resize and compress the image.

example:
http://cdn2.hubspot.net/hub/414386/file-1254903613-jpg/images/blog-1.jpg
http://cdn2.hubspot.net/hub/414386/file-1254903613-jpg/images/blog-1.jpg?width=450

very handy when dealing with srcsets

**Comment by andrewabogado** [comment]
@pgdureza Got it. Indeed, that looks handy. So need for images for the front-end build. I guess just upload to Hubspot's design manager then. Sorry, lots of questions. I'm pretty to new to Hubspot development.
